import type { Metadata } from 'next'
import '../vendor/reset.css'
import './globals.scss'
import 'swiper/css'
import { Nunito_Sans } from 'next/font/google'
import { nextArt } from '../vendor/fonts/fonts'
import Header from '../components/header/header'
import Footer from '../components/footer/footer'

const nunitoSans = Nunito_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru">
      <body className={`${nunitoSans.className} ${nextArt.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
